### ISSUE TITLE
Tiled Issues Tracker

### ISSUE THREAD

**Issue by AristurtleDev** [craftworkgames/MonoGame.Extended#848]
## Description
This issue is being created to centralize all current reported issues with using Tiled with MonoGame.Extended.  

### Priority
The following issues should be prioritized to return Tiled import and usage functionality back to MonoGame.Extended: 
- [x] Resolve `get_TransparentBlack` error when importing TSX files.  This issue occured due to the MonoGame 3.8.1.303 update which removed the `Color.TransparentBlack` value.  This was resolved in PR #735.
    - #826
    - #812 
    - #811 
    - #807 
    - #783 
    - #779, 
 - [ ] Update to support changes with current version of Tiled
     - #778 
     - #739
     - #731
     - #711 
 - [ ] Better Exception Message When using A Collection of Images
     - #700 
     - #475
     - #102 
- [ ] Tilemap not rendering properly
    - #740 
    - #738
    - #697 
    - #649 
- [ ] `InvalidCastException` when loading `TiledMap` (this may already be resolved in `develop`
      - #728
 - [ ] Update samples
     - #753
- [ ] Release Updated NuGet to support current MonoGame 3.8.1.303
    - #774

**Comment by AristurtleDev** [comment]
Closing this in favor of using #1113 for tracking
